on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.CUSTOM_TOKEN }}
          title: Title
          body: body
          assignees: |
            arpan-smartend

      - run: |
          echo ${{ steps.issue.outputs.issue }}

      - uses: ./.github/actions/hello
        id: Hello
        with:
          who-to-greet: "Arpan"

      - run: |
          echo "Time - ${{ steps.Hello.outputs.time}}"
          echo $HELLO
